name: Build
on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
            username: mambari
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build app dockerfile (with push)
        run: |
            docker buildx build \
            --no-cache \
            --platform=linux/amd64 \
            --output "type=image,push=true" \
            --file ./.dockerfile . \
            --tag mambari/openvoice:latest
